name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    environment:
      name: test
      url: https://github.com/ryutah/sample-ga/settings/environments/1307982831/edit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
