name: sample-pr

permissions:
  pull-requests: write

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: gh command existance checkk
        run: gh --help
      - name: adds pr comments
        run: gh pr comment ${{ github.event.pull_request.html_url  }} --body '## Test Comment!!!'
